<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFe5XxQ3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFe5XxQ3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFe5XxQ3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFe5XxQ3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFe5XxQ3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Fe5XxQ3',
    'container.build_id' => '8e793e85',
    'container.build_time' => 1623240887,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFe5XxQ3');
