<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVEdBKOA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVEdBKOA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVEdBKOA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVEdBKOA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVEdBKOA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VEdBKOA',
    'container.build_id' => '143175ca',
    'container.build_time' => 1626425771,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVEdBKOA');
