<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP5lvr9k\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP5lvr9k/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP5lvr9k.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP5lvr9k\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerP5lvr9k\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'P5lvr9k',
    'container.build_id' => '09e5a263',
    'container.build_time' => 1623230917,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP5lvr9k');
